"""Structural verification for SVG files generated by BookBarcode."""

from __future__ import annotations

from pathlib import Path
from xml.etree import ElementTree

from ..ean13 import GUARD_MODULES, SYMBOL_MODULES, encode_ean13
from ..isbn import validate_isbn13
from ..layout import LayoutSpec, ResolvedBarcodeLayout, resolve_layout
from .result import VerificationResult


EXPECTED_CMYK_BLACK = "0,0,0,100"


def verify_svg(
    path: str | Path,
    expected_isbn: str,
    layout: LayoutSpec | ResolvedBarcodeLayout | None = None,
) -> VerificationResult:
    """Verify SVG dimensions, modules, guard bars, text, and CMYK intent."""
    source = Path(path)
    resolved_layout = resolve_layout(layout)
    normalized_isbn = validate_isbn13(expected_isbn)
    try:
        root = ElementTree.parse(source).getroot()
    except (ElementTree.ParseError, OSError) as exc:
        return VerificationResult((f"unable to parse SVG: {exc}",))

    namespace = {"svg": "http://www.w3.org/2000/svg"}
    errors: list[str] = []
    width = _format_mm(resolved_layout.width_mm)
    height = _format_mm(resolved_layout.height_mm)
    if root.tag != "{http://www.w3.org/2000/svg}svg":
        errors.append("root element is not SVG")
    if root.get("width") != f"{width}mm":
        errors.append("width does not match the requested layout")
    if root.get("height") != f"{height}mm":
        errors.append("height does not match the requested layout")
    if root.get("viewBox") != f"0 0 {width} {height}":
        errors.append("viewBox does not match the physical dimensions")

    bars_group = root.find(".//svg:g[@id='bars']", namespace)
    if bars_group is None or bars_group.get("data-cmyk") != EXPECTED_CMYK_BLACK:
        errors.append("bars are not marked as C:0 M:0 Y:0 K:100")

    reconstructed = ["0"] * SYMBOL_MODULES
    guard_count = 0
    bars = root.findall(".//svg:g[@id='bars']/svg:rect", namespace)
    for bar in bars:
        try:
            start = int(bar.attrib["data-module"])
            width_mm = float(bar.attrib["width"])
            height_mm = float(bar.attrib["height"])
            x_mm = float(bar.attrib["x"])
            y_mm = float(bar.attrib["y"])
        except (KeyError, TypeError, ValueError):
            errors.append("a bar contains missing or invalid geometry")
            continue
        measured_modules = width_mm / resolved_layout.module_width_mm
        module_count = round(measured_modules)
        if module_count < 1:
            errors.append("a bar has no measurable modules")
            continue
        if abs(measured_modules - module_count) > 0.001:
            errors.append("a bar width is not an integer number of modules")
        expected_x = (
            resolved_layout.symbol_left_mm
            + start * resolved_layout.module_width_mm
        )
        if abs(x_mm - expected_x) > 0.001:
            errors.append("a bar x-position does not match its module index")
        if abs(y_mm - resolved_layout.bar_top_mm) > 0.001:
            errors.append("a bar y-position does not match the layout")

        run_modules = range(start, start + module_count)
        expected_guard = all(module in GUARD_MODULES for module in run_modules)
        expected_class = "guard" if expected_guard else "data"
        if bar.get("class") != expected_class:
            errors.append("a bar has an incorrect guard/data class")
        for module in range(start, start + module_count):
            if not 0 <= module < SYMBOL_MODULES:
                errors.append("a bar extends outside the 95-module symbol")
            elif reconstructed[module] == "1":
                errors.append("bar modules overlap")
            else:
                reconstructed[module] = "1"
        if expected_guard:
            guard_count += 1
        expected_height = resolved_layout.data_bar_height_mm
        if expected_guard:
            expected_height += resolved_layout.guard_extension_mm
        if abs(height_mm - expected_height) > 0.001:
            errors.append("a bar height does not match its class")

    if "".join(reconstructed) != encode_ean13(normalized_isbn):
        errors.append("bar modules do not encode the expected ISBN")
    if guard_count != 6:
        errors.append("the six guard bars are not all present")
    readable = root.findall(
        ".//svg:g[@id='human-readable']/svg:text", namespace
    )
    if "".join(item.text or "" for item in readable) != normalized_isbn:
        errors.append("human-readable digits do not match the expected ISBN")
    return VerificationResult(tuple(errors))


def _format_mm(value: float) -> str:
    """Independently format the four-decimal SVG millimetre convention."""
    return f"{value:.4f}".rstrip("0").rstrip(".")
